# Dependencies
markdown:         redcarpet
highlighter:      pygments

gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Kostadin's Corner
tagline:          'veni vidi vici refactor'
description:      'veni vidi vici refactor <br> Personal website for Kostadin Golev'
url:              http://kotse.github.io/
baseurl:          /

author:
  name:           'Kostadin Golev'
  url:            https://twitter.com/kotseto

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kotse/kotse.github.io
